//------------------------------------------------------------------------------
// Terminal API
//
// Copyright (C)2026 Matt Davies, all rights reserved
//------------------------------------------------------------------------------
#include <term/term.h>

//------------------------------------------------------------------------------

#include <locale.h>
#include <wchar.h>

Term g_term;
bool g_cursor_visible      = true;
bool g_cursor_dirty        = true;
int  g_cursor_x            = 0;
int  g_cursor_y            = 0;
u32  g_cursor_ink          = 0xFFFFFF;
u32  g_cursor_paper        = 0x000000;

Array(u32) g_term_fb_chars = NULL;
Array(u32) g_term_fb_ink   = NULL;
Array(u32) g_term_fb_paper = NULL;
Array(u8) g_term_fb_dirty  = NULL;
TermSize g_term_fb_size    = {0};
Arena    g_term_arena;

internal void _term_queue_event(TermEvent event);
internal void _term_queue_mouse(u16 x, u16 y, i16 wheel, u8 buttons);
internal void _term_alt_enter();
internal void _term_alt_leave();
internal void _term_raw_enter();
internal void _term_raw_leave();

void _term_fb_resize(u16 width, u16 height);
void _term_fb_done();
bool _term_fb_has_dirty(void);
void _term_fb_present_now(void);

internal void _term_start(void);
internal void _term_stop(void);
internal void _term_check_resize(void);
internal void _term_maybe_present(void);

//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// Character width helpers
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

typedef struct {
    int first;
    int last;
} TermInterval;

internal int _term_bisearch(wchar_t ucs, const TermInterval* table, int max)
{
    int min = 0;
    int mid;

    if (ucs < table[0].first || ucs > table[max].last) {
        return 0;
    }
    while (max >= min) {
        mid = (min + max) / 2;
        if (ucs > table[mid].last) {
            min = mid + 1;
        } else if (ucs < table[mid].first) {
            max = mid - 1;
        } else {
            return 1;
        }
    }

    return 0;
}

int _term_wcwidth(u32 ucs)
{
    /* sorted list of non-overlapping intervals of non-spacing characters */
    /* generated by "uniset +cat=Me +cat=Mn +cat=Cf -00AD +1160-11FF +200B c" */
    static const TermInterval combining[] = {
        {0x0300, 0x036F},   {0x0483, 0x0486},   {0x0488, 0x0489},
        {0x0591, 0x05BD},   {0x05BF, 0x05BF},   {0x05C1, 0x05C2},
        {0x05C4, 0x05C5},   {0x05C7, 0x05C7},   {0x0600, 0x0603},
        {0x0610, 0x0615},   {0x064B, 0x065E},   {0x0670, 0x0670},
        {0x06D6, 0x06E4},   {0x06E7, 0x06E8},   {0x06EA, 0x06ED},
        {0x070F, 0x070F},   {0x0711, 0x0711},   {0x0730, 0x074A},
        {0x07A6, 0x07B0},   {0x07EB, 0x07F3},   {0x0901, 0x0902},
        {0x093C, 0x093C},   {0x0941, 0x0948},   {0x094D, 0x094D},
        {0x0951, 0x0954},   {0x0962, 0x0963},   {0x0981, 0x0981},
        {0x09BC, 0x09BC},   {0x09C1, 0x09C4},   {0x09CD, 0x09CD},
        {0x09E2, 0x09E3},   {0x0A01, 0x0A02},   {0x0A3C, 0x0A3C},
        {0x0A41, 0x0A42},   {0x0A47, 0x0A48},   {0x0A4B, 0x0A4D},
        {0x0A70, 0x0A71},   {0x0A81, 0x0A82},   {0x0ABC, 0x0ABC},
        {0x0AC1, 0x0AC5},   {0x0AC7, 0x0AC8},   {0x0ACD, 0x0ACD},
        {0x0AE2, 0x0AE3},   {0x0B01, 0x0B01},   {0x0B3C, 0x0B3C},
        {0x0B3F, 0x0B3F},   {0x0B41, 0x0B43},   {0x0B4D, 0x0B4D},
        {0x0B56, 0x0B56},   {0x0B82, 0x0B82},   {0x0BC0, 0x0BC0},
        {0x0BCD, 0x0BCD},   {0x0C3E, 0x0C40},   {0x0C46, 0x0C48},
        {0x0C4A, 0x0C4D},   {0x0C55, 0x0C56},   {0x0CBC, 0x0CBC},
        {0x0CBF, 0x0CBF},   {0x0CC6, 0x0CC6},   {0x0CCC, 0x0CCD},
        {0x0CE2, 0x0CE3},   {0x0D41, 0x0D43},   {0x0D4D, 0x0D4D},
        {0x0DCA, 0x0DCA},   {0x0DD2, 0x0DD4},   {0x0DD6, 0x0DD6},
        {0x0E31, 0x0E31},   {0x0E34, 0x0E3A},   {0x0E47, 0x0E4E},
        {0x0EB1, 0x0EB1},   {0x0EB4, 0x0EB9},   {0x0EBB, 0x0EBC},
        {0x0EC8, 0x0ECD},   {0x0F18, 0x0F19},   {0x0F35, 0x0F35},
        {0x0F37, 0x0F37},   {0x0F39, 0x0F39},   {0x0F71, 0x0F7E},
        {0x0F80, 0x0F84},   {0x0F86, 0x0F87},   {0x0F90, 0x0F97},
        {0x0F99, 0x0FBC},   {0x0FC6, 0x0FC6},   {0x102D, 0x1030},
        {0x1032, 0x1032},   {0x1036, 0x1037},   {0x1039, 0x1039},
        {0x1058, 0x1059},   {0x1160, 0x11FF},   {0x135F, 0x135F},
        {0x1712, 0x1714},   {0x1732, 0x1734},   {0x1752, 0x1753},
        {0x1772, 0x1773},   {0x17B4, 0x17B5},   {0x17B7, 0x17BD},
        {0x17C6, 0x17C6},   {0x17C9, 0x17D3},   {0x17DD, 0x17DD},
        {0x180B, 0x180D},   {0x18A9, 0x18A9},   {0x1920, 0x1922},
        {0x1927, 0x1928},   {0x1932, 0x1932},   {0x1939, 0x193B},
        {0x1A17, 0x1A18},   {0x1B00, 0x1B03},   {0x1B34, 0x1B34},
        {0x1B36, 0x1B3A},   {0x1B3C, 0x1B3C},   {0x1B42, 0x1B42},
        {0x1B6B, 0x1B73},   {0x1DC0, 0x1DCA},   {0x1DFE, 0x1DFF},
        {0x200B, 0x200F},   {0x202A, 0x202E},   {0x2060, 0x2063},
        {0x206A, 0x206F},   {0x20D0, 0x20EF},   {0x302A, 0x302F},
        {0x3099, 0x309A},   {0xA806, 0xA806},   {0xA80B, 0xA80B},
        {0xA825, 0xA826},   {0xFB1E, 0xFB1E},   {0xFE00, 0xFE0F},
        {0xFE20, 0xFE23},   {0xFEFF, 0xFEFF},   {0xFFF9, 0xFFFB},
        {0x10A01, 0x10A03}, {0x10A05, 0x10A06}, {0x10A0C, 0x10A0F},
        {0x10A38, 0x10A3A}, {0x10A3F, 0x10A3F}, {0x1D167, 0x1D169},
        {0x1D173, 0x1D182}, {0x1D185, 0x1D18B}, {0x1D1AA, 0x1D1AD},
        {0x1D242, 0x1D244}, {0xE0001, 0xE0001}, {0xE0020, 0xE007F},
        {0xE0100, 0xE01EF}};

    /* test for 8-bit control characters */
    if (ucs == 0) {
        return 0;
    }
    if (ucs < 32 || (ucs >= 0x7f && ucs < 0xa0)) {
        return -1;
    }

    /* binary search in table of non-spacing characters */
    if (_term_bisearch(
            ucs, combining, sizeof(combining) / sizeof(TermInterval) - 1)) {
        return 0;
    }

    /* if we arrive here, ucs is not a combining or C0/C1 control character */

    return 1 +
           (ucs >= 0x1100 &&
            (ucs <= 0x115f || /* Hangul Jamo init. consonants */
             ucs == 0x2329 || ucs == 0x232a ||
             (ucs >= 0x2e80 && ucs <= 0xa4cf &&
              ucs != 0x303f) ||                  /* CJK ... Yi */
             (ucs >= 0xac00 && ucs <= 0xd7a3) || /* Hangul Syllables */
             (ucs >= 0xf900 &&
              ucs <= 0xfaff) || /* CJK Compatibility Ideographs */
             (ucs >= 0xfe10 && ucs <= 0xfe19) || /* Vertical forms */
             (ucs >= 0xfe30 && ucs <= 0xfe6f) || /* CJK Compatibility Forms */
             (ucs >= 0xff00 && ucs <= 0xff60) || /* Fullwidth Forms */
             (ucs >= 0xffe0 && ucs <= 0xffe6) ||
             (ucs >= 0x20000 && ucs <= 0x2fffd) ||
             (ucs >= 0x30000 && ucs <= 0x3fffd)));
}

//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// WINDOWS IMPLEMENTATION
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

#if OS_WINDOWS

global_variable HANDLE g_term_console_input         = INVALID_HANDLE_VALUE;
global_variable DWORD  g_term_console_input_mode    = 0;
global_variable bool   g_term_console_mode_captured = false;

//------------------------------------------------------------------------------

TermSize term_size_get(void)
{
    TermSize term_size = {0};

    CONSOLE_SCREEN_BUFFER_INFO info;
    if (GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &info)) {
        term_size.width  = info.srWindow.Right - info.srWindow.Left + 1;
        term_size.height = info.srWindow.Bottom - info.srWindow.Top + 1;
    } else {
        eprn("Failed to get terminal size on Windows");
        abort();
    }

    return term_size;
}

//------------------------------------------------------------------------------

internal void _term_platform_init()
{
    HANDLE console = GetStdHandle(STD_OUTPUT_HANDLE);
    if (console != INVALID_HANDLE_VALUE) {
        DWORD mode;
        if (GetConsoleMode(console, &mode)) {
            SetConsoleMode(console, mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
        }
    }

    TermSize size = term_size_get();
    g_term.size   = size;
    _term_fb_resize(size.width, size.height);

    TermEvent event;
    event.kind = TERM_EVENT_RESIZE;
    event.size = size;
    _term_queue_event(event);
}

//------------------------------------------------------------------------------

bool term_loop()
{
    if (g_term.running) {

        // Windows-specific event polling can be added here
        // We need to check any console events and handle them
        HANDLE console = GetStdHandle(STD_INPUT_HANDLE);
        if (console != INVALID_HANDLE_VALUE) {
            DWORD events;
            GetNumberOfConsoleInputEvents(console, &events);
            while (events > 0) {
                INPUT_RECORD record;
                DWORD        read;
                ReadConsoleInputA(console, &record, 1, &read);

                switch (record.EventType) {
                case WINDOW_BUFFER_SIZE_EVENT:
                    {
                        g_term.size = term_size_get();
                        TermEvent event;
                        event.kind = TERM_EVENT_RESIZE;
                        event.size = g_term.size;
                        _term_queue_event(event);
                        _term_fb_resize(g_term.size.width, g_term.size.height);
                    }
                    break;

                case KEY_EVENT:
                    if (record.Event.KeyEvent.bKeyDown) {
                        TermEvent event;
                        event.kind = TERM_EVENT_KEY;
                        event.key  = record.Event.KeyEvent.uChar.AsciiChar;
                        _term_queue_event(event);
                    }
                    break;

                case MOUSE_EVENT:
                    {
                        MOUSE_EVENT_RECORD mouse = record.Event.MouseEvent;
                        u8                 buttons = 0;
                        i16                wheel   = 0;

                        if (mouse.dwButtonState & FROM_LEFT_1ST_BUTTON_PRESSED) {
                            buttons |= 0x1;
                        }
                        if (mouse.dwButtonState & RIGHTMOST_BUTTON_PRESSED) {
                            buttons |= 0x2;
                        }
                        if (mouse.dwButtonState & FROM_LEFT_2ND_BUTTON_PRESSED) {
                            buttons |= 0x4;
                        }

                        if ((mouse.dwEventFlags & MOUSE_WHEELED) != 0) {
                            wheel = (SHORT)HIWORD(mouse.dwButtonState) > 0 ? 1 : -1;
                        }

                        _term_queue_mouse((u16)mouse.dwMousePosition.X,
                                          (u16)mouse.dwMousePosition.Y,
                                          wheel,
                                          buttons);
                    }
                    break;
                }
                events--;
            }
        }
        _term_maybe_present();
        return true;
    } else {
        _term_stop();
        return false;
    }
}

//------------------------------------------------------------------------------

internal void _term_raw_enter(void)
{
    HANDLE input = GetStdHandle(STD_INPUT_HANDLE);
    if (input == INVALID_HANDLE_VALUE) {
        eprn("Failed to get console input handle");
        abort();
    }

    DWORD mode = 0;
    if (!GetConsoleMode(input, &mode)) {
        eprn("Failed to get console input mode");
        abort();
    }

    g_term_console_input         = input;
    g_term_console_input_mode    = mode;
    g_term_console_mode_captured = true;

    DWORD raw_mode               = mode;
    raw_mode &=
        ~(ENABLE_LINE_INPUT | ENABLE_ECHO_INPUT | ENABLE_PROCESSED_INPUT);
    raw_mode |= (ENABLE_WINDOW_INPUT | ENABLE_EXTENDED_FLAGS | ENABLE_MOUSE_INPUT);
    raw_mode &= ~(ENABLE_QUICK_EDIT_MODE | ENABLE_INSERT_MODE);

    if (!SetConsoleMode(input, raw_mode)) {
        eprn("Failed to set raw console input mode");
        abort();
    }

    FlushConsoleInputBuffer(input);
}

internal void _term_raw_leave(void)
{
    if (!g_term_console_mode_captured ||
        g_term_console_input == INVALID_HANDLE_VALUE) {
        return;
    }

    if (!SetConsoleMode(g_term_console_input, g_term_console_input_mode)) {
        eprn("Failed to restore console input mode");
        abort();
    }

    g_term_console_mode_captured = false;
}

//------------------------------------------------------------------------------

#endif // OS_WINDOWS

//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// LINUX/MACOSX IMPLEMENTATION
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

#if OS_POSIX

#    include <signal.h>
#    include <string.h>
#    include <sys/ioctl.h>
#    include <termios.h>

// Signals when the terminal resizes
global_variable volatile sig_atomic_t g_term_resize_signal = 0;
global_variable struct termios        g_term_original_tios;
global_variable char                  g_term_pending_bytes[32];
global_variable usize                 g_term_pending_count = 0;
global_variable usize                 g_term_pending_index = 0;
global_variable char                  g_term_escape_bytes[32];
global_variable usize                 g_term_escape_count = 0;

//------------------------------------------------------------------------------

internal void _term_queue_key(char c)
{
    TermEvent event;
    event.kind = TERM_EVENT_KEY;
    event.key  = c;
    _term_queue_event(event);
}

internal void _term_queue_mouse(u16 x, u16 y, i16 wheel, u8 buttons)
{
    TermEvent event;
    event.kind         = TERM_EVENT_MOUSE;
    event.mouse.x      = x;
    event.mouse.y      = y;
    event.mouse.wheel  = wheel;
    event.mouse.buttons = buttons;
    _term_queue_event(event);
}

internal bool _term_posix_try_read_byte(char* out_c)
{
    int nread = read(STDIN_FILENO, out_c, 1);
    return nread == 1;
}

internal void _term_posix_buffer_pending(const char* bytes, usize count)
{
    if (count == 0) {
        g_term_pending_count = 0;
        g_term_pending_index = 0;
        return;
    }

    count = MIN(count, ARRAY_COUNT(g_term_pending_bytes));
    memcpy(g_term_pending_bytes, bytes, count);
    g_term_pending_count = count;
    g_term_pending_index = 0;
}

internal bool _term_parse_u16_bytes(const char* bytes, usize count, u16* out_value)
{
    u64 value = 0;
    if (count == 0) {
        return false;
    }

    for (usize i = 0; i < count; i++) {
        char c = bytes[i];
        if (c < '0' || c > '9') {
            return false;
        }
        value = value * 10 + (u64)(c - '0');
        if (value > 65535) {
            return false;
        }
    }

    *out_value = (u16)value;
    return true;
}

internal void _term_posix_shift_escape(usize consumed)
{
    if (consumed >= g_term_escape_count) {
        g_term_escape_count = 0;
        return;
    }

    memmove(g_term_escape_bytes,
            g_term_escape_bytes + consumed,
            g_term_escape_count - consumed);
    g_term_escape_count -= consumed;
}

internal bool _term_posix_decode_mouse_sgr(const char* bytes,
                                           usize       count,
                                           usize*      out_consumed)
{
    if (count < 6 || bytes[0] != '\033' || bytes[1] != '[' || bytes[2] != '<') {
        return false;
    }

    usize first_sep  = 0;
    usize second_sep = 0;
    usize final_pos  = 0;
    for (usize i = 3; i < count; i++) {
        if (bytes[i] == ';') {
            if (first_sep == 0) {
                first_sep = i;
            } else if (second_sep == 0) {
                second_sep = i;
            }
        } else if (bytes[i] == 'M' || bytes[i] == 'm') {
            final_pos = i;
            break;
        }
    }

    if (first_sep == 0 || second_sep == 0 || final_pos == 0) {
        return false;
    }

    u16 cb = 0;
    u16 cx = 0;
    u16 cy = 0;
    if (!_term_parse_u16_bytes(bytes + 3, first_sep - 3, &cb) ||
        !_term_parse_u16_bytes(bytes + first_sep + 1,
                               second_sep - first_sep - 1,
                               &cx) ||
        !_term_parse_u16_bytes(
            bytes + second_sep + 1, final_pos - second_sep - 1, &cy)) {
        return false;
    }

    u8  buttons = 0;
    i16 wheel   = 0;
    u16 base    = cb & 0x3;
    if ((cb & 0x40) != 0) {
        wheel = base == 0 ? 1 : -1;
    } else if (bytes[final_pos] == 'M') {
        if (base == 0) {
            buttons = 0x1;
        } else if (base == 1) {
            buttons = 0x4;
        } else if (base == 2) {
            buttons = 0x2;
        }
    }

    _term_queue_mouse(cx > 0 ? cx - 1 : 0, cy > 0 ? cy - 1 : 0, wheel, buttons);
    *out_consumed = final_pos + 1;
    return true;
}

internal bool _term_posix_decode_mouse_1015(const char* bytes,
                                            usize       count,
                                            usize*      out_consumed)
{
    if (count < 7 || bytes[0] != '\033' || bytes[1] != '[') {
        return false;
    }
    if (bytes[2] < '0' || bytes[2] > '9') {
        return false;
    }

    usize first_sep  = 0;
    usize second_sep = 0;
    usize final_pos  = 0;
    for (usize i = 2; i < count; i++) {
        if (bytes[i] == ';') {
            if (first_sep == 0) {
                first_sep = i;
            } else if (second_sep == 0) {
                second_sep = i;
            }
        } else if (bytes[i] == 'M') {
            final_pos = i;
            break;
        }
    }

    if (first_sep == 0 || second_sep == 0 || final_pos == 0) {
        return false;
    }

    u16 cb = 0;
    u16 cx = 0;
    u16 cy = 0;
    if (!_term_parse_u16_bytes(bytes + 2, first_sep - 2, &cb) ||
        !_term_parse_u16_bytes(bytes + first_sep + 1,
                               second_sep - first_sep - 1,
                               &cx) ||
        !_term_parse_u16_bytes(
            bytes + second_sep + 1, final_pos - second_sep - 1, &cy)) {
        return false;
    }

    u8  buttons = 0;
    i16 wheel   = 0;
    u16 base    = cb & 0x3;
    if ((cb & 0x40) != 0) {
        wheel = base == 0 ? 1 : -1;
    } else if (base == 0) {
        buttons = 0x1;
    } else if (base == 1) {
        buttons = 0x4;
    } else if (base == 2) {
        buttons = 0x2;
    }

    _term_queue_mouse(cx > 0 ? cx - 1 : 0, cy > 0 ? cy - 1 : 0, wheel, buttons);
    *out_consumed = final_pos + 1;
    return true;
}

internal bool _term_posix_decode_mouse_x10(const char* bytes,
                                           usize       count,
                                           usize*      out_consumed)
{
    if (count < 6 || bytes[0] != '\033' || bytes[1] != '[' || bytes[2] != 'M') {
        return false;
    }

    u8 cb = (u8)bytes[3] - 32;
    u8 cx = (u8)bytes[4] - 32;
    u8 cy = (u8)bytes[5] - 32;

    u8  buttons = 0;
    i16 wheel   = 0;
    u8  base    = cb & 0x3;
    if ((cb & 0x40) != 0) {
        wheel = base == 0 ? 1 : -1;
    } else if (base == 0) {
        buttons = 0x1;
    } else if (base == 1) {
        buttons = 0x4;
    } else if (base == 2) {
        buttons = 0x2;
    }

    _term_queue_mouse(cx > 0 ? (u16)(cx - 1) : 0,
                      cy > 0 ? (u16)(cy - 1) : 0,
                      wheel,
                      buttons);
    *out_consumed = 6;
    return true;
}

internal bool _term_posix_swallow_mouse_tail(char first)
{
    if (first != ';') {
        return false;
    }

    char  tail[32];
    usize count = 0;
    tail[count++] = first;

    char next;
    while (count < ARRAY_COUNT(tail) && _term_posix_try_read_byte(&next)) {
        tail[count++] = next;
    }

    if (count < 3) {
        _term_queue_key(first);
        if (count > 1) {
            _term_posix_buffer_pending(tail + 1, count - 1);
        }
        return true;
    }

    if (tail[count - 1] != 'M') {
        _term_queue_key(first);
        if (count > 1) {
            _term_posix_buffer_pending(tail + 1, count - 1);
        }
        return true;
    }

    for (usize i = 1; i + 1 < count; i++) {
        if ((tail[i] < '0' || tail[i] > '9') && tail[i] != ';') {
            _term_queue_key(first);
            _term_posix_buffer_pending(tail + 1, count - 1);
            return true;
        }
    }

    return true;
}

internal bool _term_posix_try_drain_escape(void)
{
    char next;
    while (g_term_escape_count < ARRAY_COUNT(g_term_escape_bytes) &&
           _term_posix_try_read_byte(&next)) {
        g_term_escape_bytes[g_term_escape_count++] = next;
    }

    if (g_term_escape_count < 2 || g_term_escape_bytes[0] != '\033') {
        return false;
    }

    if (g_term_escape_count == 1) {
        return false;
    }

    if (g_term_escape_bytes[1] == 'O') {
        for (usize i = 2; i < g_term_escape_count; i++) {
            char final = g_term_escape_bytes[i];
            if (final >= '@' && final <= '~') {
                _term_posix_shift_escape(i + 1);
                return true;
            }
        }
        return false;
    }

    if (g_term_escape_bytes[1] != '[') {
        _term_queue_key(g_term_escape_bytes[0]);
        _term_posix_buffer_pending(
            g_term_escape_bytes + 1, g_term_escape_count - 1);
        g_term_escape_count = 0;
        return true;
    }

    usize consumed = 0;

    if (g_term_escape_count >= 6 && g_term_escape_bytes[2] == 'M' &&
        _term_posix_decode_mouse_x10(
            g_term_escape_bytes, g_term_escape_count, &consumed)) {
        _term_posix_shift_escape(consumed);
        return true;
    }

    if (g_term_escape_count >= 3 && g_term_escape_bytes[2] == '<') {
        for (usize i = 3; i < g_term_escape_count; i++) {
            if (g_term_escape_bytes[i] == 'm' || g_term_escape_bytes[i] == 'M') {
                if (_term_posix_decode_mouse_sgr(
                        g_term_escape_bytes, g_term_escape_count, &consumed)) {
                    _term_posix_shift_escape(consumed);
                }
                return true;
            }
        }
        return false;
    }

    if (g_term_escape_count >= 3 &&
        g_term_escape_bytes[2] >= '0' && g_term_escape_bytes[2] <= '9') {
        for (usize i = 2; i < g_term_escape_count; i++) {
            if (g_term_escape_bytes[i] == 'M') {
                if (_term_posix_decode_mouse_1015(
                        g_term_escape_bytes, g_term_escape_count, &consumed)) {
                    _term_posix_shift_escape(consumed);
                }
                return true;
            }
        }
        return false;
    }

    if (g_term_escape_count >= 3) {
        for (usize i = 2; i < g_term_escape_count; i++) {
            char final = g_term_escape_bytes[i];
            if (final >= '@' && final <= '~') {
                _term_posix_shift_escape(i + 1);
                return true;
            }
        }
    }

    return false;
}

//------------------------------------------------------------------------------

TermSize term_size_get(void)
{
    TermSize term_size = {0};

    struct winsize w;
    if (ioctl(STDOUT_FILENO, TIOCGWINSZ, &w) == 0) {
        term_size.width  = w.ws_col;
        term_size.height = w.ws_row;
    } else {
        eprn("Failed to get terminal size on Unix");
        abort();
    }

    return term_size;
}

//------------------------------------------------------------------------------

internal void _term_raw_enter(void)
{
    tcgetattr(STDIN_FILENO, &g_term_original_tios);
    struct termios raw_tios = g_term_original_tios;

    raw_tios.c_lflag &= ~(ECHO | ICANON | ISIG | IEXTEN);
    raw_tios.c_iflag &= ~(IXON | ICRNL | BRKINT | INPCK | ISTRIP);
    raw_tios.c_oflag &= ~(OPOST);
    raw_tios.c_cflag |= (CS8);

    // Set read timeout
    raw_tios.c_cc[VMIN]  = 0;
    raw_tios.c_cc[VTIME] = 0;

    tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw_tios);
    g_term_pending_count = 0;
    g_term_pending_index = 0;
    g_term_escape_count  = 0;
}

internal void _term_raw_leave(void)
{
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &g_term_original_tios);
}

internal void _term_raw_key(void)
{
    if (g_term_pending_index < g_term_pending_count) {
        _term_queue_key(g_term_pending_bytes[g_term_pending_index++]);
        if (g_term_pending_index == g_term_pending_count) {
            g_term_pending_count = 0;
            g_term_pending_index = 0;
        }
        return;
    }

    if (g_term_escape_count > 0) {
        _term_posix_try_drain_escape();
        return;
    }

    char first;
    if (!_term_posix_try_read_byte(&first)) {
        return;
    }

    if (first != '\033') {
        if (_term_posix_swallow_mouse_tail(first)) {
            return;
        }
        _term_queue_key(first);
        return;
    }

    g_term_escape_bytes[0] = first;
    g_term_escape_count    = 1;
    _term_posix_try_drain_escape();
}

//------------------------------------------------------------------------------

internal void _term_on_winch(int sig)
{
    UNUSED(sig);
    g_term_resize_signal = 1;
}

internal void _term_install_resize_handler(void)
{
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = _term_on_winch;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = SA_RESTART;
    sigaction(SIGWINCH, &sa, NULL);
}

internal void _term_remove_resize_handler(void)
{
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = SIG_DFL;
    sigaction(SIGWINCH, &sa, NULL);
}

//------------------------------------------------------------------------------

internal void _term_platform_init(void)
{
    _term_install_resize_handler();

    // Force the sending of at least one resize event so we can react to the
    // initial size.  Windows does this already, we make POSIX systems do the
    // same.
    g_term_resize_signal = 1;
}

//------------------------------------------------------------------------------

bool term_loop(void)
{
    if (g_term.running) {

        // Check for terminal resize signal
        _term_check_resize();
        _term_raw_key();
        _term_maybe_present();
        return true;
    } else {
        // Unregister the signal handler
        _term_remove_resize_handler();
        _term_stop();
        return false;
    }
}

//------------------------------------------------------------------------------

#endif // OS_POSIX

//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// S H A R E D   I M P L E M E N T A T I O N
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

void dump_term_size(void)
{
    prn(ANSI_YELLOW "┌──────────────────┬──────────┐");
    pr(ANSI_YELLOW "│ " ANSI_CYAN "Terminal Columns");
    prn(ANSI_YELLOW " │ " ANSI_GREEN "%5u " ANSI_YELLOW "   │",
        g_term.size.width);
    pr(ANSI_YELLOW "│ " ANSI_CYAN "Terminal Rows");
    prn(ANSI_YELLOW "    │ " ANSI_GREEN "%5u " ANSI_YELLOW "   │",
        g_term.size.height);
    prn(ANSI_YELLOW "└──────────────────┴──────────┘");
}

void dump_term_size_raw(void)
{
    term_cursor_goto(0, 0);
    pr(ANSI_YELLOW "┌──────────────────┬──────────┐");
    term_cursor_goto(0, 1);
    pr(ANSI_YELLOW "│ " ANSI_CYAN "Terminal Columns");
    prn(ANSI_YELLOW " │ " ANSI_GREEN "%5u " ANSI_YELLOW "   │",
        g_term.size.width);
    term_cursor_goto(0, 2);
    pr(ANSI_YELLOW "│ " ANSI_CYAN "Terminal Rows");
    prn(ANSI_YELLOW "    │ " ANSI_GREEN "%5u " ANSI_YELLOW "   │",
        g_term.size.height);
    term_cursor_goto(0, 3);
    prn(ANSI_YELLOW "└──────────────────┴──────────┘");
}

//------------------------------------------------------------------------------

internal void _term_queue_event(TermEvent event)
{
    array_push(g_term.event_queue, event);
}

//------------------------------------------------------------------------------

internal void _term_alt_enter(void)
{
    pr("\x1b[?1049h\x1b[?1007l\x1b[?1002h\x1b[?1006h");
}

internal void _term_alt_leave(void)
{
    pr("\x1b[?1002l\x1b[?1006l\x1b[?1007h\x1b[?1049l");
}

//------------------------------------------------------------------------------

internal void _term_start(void)
{
    _term_platform_init();
    _term_alt_enter();
    _term_raw_enter();
}

internal void _term_stop(void)
{
    array_free(g_term.event_queue);
    _term_fb_done();
    term_cursor_show();
    _term_alt_leave();
    _term_raw_leave();
    arena_done(&g_term_arena);
}

//------------------------------------------------------------------------------

internal void _term_check_resize()
{
    TermSize new_size = term_size_get();
    if (new_size.width != g_term.size.width ||
        new_size.height != g_term.size.height) {
        g_term.size = new_size;
        TermEvent event;
        event.kind = TERM_EVENT_RESIZE;
        event.size = g_term.size;
        _term_queue_event(event);
        _term_fb_resize(new_size.width, new_size.height);
    }
}

internal void _term_maybe_present(void)
{
    if (g_cursor_dirty || _term_fb_has_dirty()) {
        _term_fb_present_now();
        g_cursor_dirty           = false;
    }
}

//------------------------------------------------------------------------------

void term_init(void)
{
    if (g_term.initialised) {
        return;
    }

    setlocale(LC_CTYPE, "");

    // Initialise the terminal, ready for a loop
    g_term.size        = (TermSize){0};
    g_term.running     = true;
    g_term.initialised = true;

    arena_init(&g_term_arena, .reserved_size = MB(128), .grow_rate = 1);

    _term_start();
    _term_check_resize();
}

//------------------------------------------------------------------------------

void term_done(void) { g_term.running = false; }

//------------------------------------------------------------------------------

void term_cls(void) { pr("\x1b[2J\x1b[3J\x1b[H"); }

//------------------------------------------------------------------------------

TermEvent term_poll_event(void)
{
    TermEvent event;
    if (array_count(g_term.event_queue) > 0) {
        event = g_term.event_queue[0];
        array_delete(g_term.event_queue, 0);
    } else {
        event.kind = TERM_EVENT_NONE;
    }
    return event;
}

//------------------------------------------------------------------------------

void term_cursor_show(void)
{
    pr("\x1b[?25h");
    g_cursor_visible = true;
    g_cursor_dirty   = true;
}

void term_cursor_hide(void)
{
    pr("\x1b[?25l");
    g_cursor_visible = false;
    g_cursor_dirty   = true;
}

//------------------------------------------------------------------------------

void term_cursor_goto(int x, int y)
{
    if (y < 0 || x < 0) {
        TermSize size = term_size_get();
        if (y < 0) {
            y = size.height + y;
        }
        if (x < 0) {
            x = size.width + x;
        }
    }
    g_cursor_x = x;
    g_cursor_y = y;
    g_cursor_dirty = true;
    ++x;
    ++y;
    pr("\x1b[%d;%dH", y, x);
}

void term_cursor_move(int dx, int dy)
{
    if (dy > 0) {
        term_cursor_down(dy);
    } else if (dy < 0) {
        term_cursor_up(-dy);
    }

    if (dx > 0) {
        term_cursor_right(dx);
    } else if (dx < 0) {
        term_cursor_left(-dx);
    }
}

void term_cursor_home(void) { pr("\x1b[H"); }

void term_cursor_up(int delta)
{
    if (delta < 0) {
        term_cursor_down(-delta);
    } else {
        pr("\x1b[%dA", delta);
    }
}

void term_cursor_down(int delta)
{
    if (delta < 0) {
        term_cursor_up(-delta);
    } else {
        pr("\x1b[%dB", delta);
    }
}

void term_cursor_right(int delta)
{
    if (delta < 0) {
        term_cursor_left(-delta);
    } else {
        pr("\x1b[%dC", delta);
    }
}

void term_cursor_left(int delta)
{
    if (delta < 0) {
        term_cursor_right(-delta);
    } else {
        pr("\x1b[%dD", delta);
    }
}

void term_cursor_colour(u32 ink, u32 paper)
{
    g_cursor_ink   = ink;
    g_cursor_paper = paper;
    g_cursor_dirty = true;
    u8 ink_r   = (ink >> 16) & 0xFF;
    u8 ink_g   = (ink >> 8) & 0xFF;
    u8 ink_b   = (ink >> 0) & 0xFF;
    u8 paper_r = (paper >> 16) & 0xFF;
    u8 paper_g = (paper >> 8) & 0xFF;
    u8 paper_b = (paper >> 0) & 0xFF;
    pr("\x1b[38;2;%d;%d;%dm", ink_r, ink_g, ink_b);
    pr("\x1b[48;2;%d;%d;%dm", paper_r, paper_g, paper_b);
}
