//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// Theme database
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

#include <term/term.h>

ColourTheme g_themes[] = {
    // Default theme
    {
        .ink             = COLOUR_WHITE,
        .paper           = COLOUR_BLACK,
        .highlight_ink   = COLOUR_BLACK,
        .highlight_paper = COLOUR_WHITE,
        .cursor          = COLOUR_WHITE,
        .gutter          = COLOUR_GREY,
        .selection       = COLOUR_BRIGHT_BLUE,
        .status_fg       = COLOUR_BLACK,
        .status_bg       = COLOUR_BRIGHT_GREY,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_BRIGHT_CYAN,
        .link            = COLOUR_BRIGHT_BLUE,
        .link_visited    = COLOUR_BRIGHT_MAGENTA,
    },
    // Blue theme
    {
        .ink             = COLOUR_WHITE,
        .paper           = COLOUR_BLUE,
        .highlight_ink   = COLOUR_BLUE,
        .highlight_paper = COLOUR_WHITE,
        .cursor          = COLOUR_WHITE,
        .gutter          = COLOUR_GREY,
        .selection       = COLOUR_BRIGHT_CYAN,
        .status_fg       = COLOUR_BLUE,
        .status_bg       = COLOUR_WHITE,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_BRIGHT_CYAN,
        .link            = COLOUR_BRIGHT_BLUE,
        .link_visited    = COLOUR_BRIGHT_MAGENTA,
    },
    // Green theme
    {
        .ink             = COLOUR_BLACK,
        .paper           = COLOUR_PASTEL_GREEN,
        .highlight_ink   = COLOUR_PASTEL_GREEN,
        .highlight_paper = COLOUR_BLACK,
        .cursor          = COLOUR_BLACK,
        .gutter          = COLOUR_PASTEL_BLACK,
        .selection       = COLOUR_PASTEL_BLUE,
        .status_fg       = COLOUR_BLACK,
        .status_bg       = COLOUR_PASTEL_YELLOW,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_BRIGHT_CYAN,
        .link            = COLOUR_BRIGHT_BLUE,
        .link_visited    = COLOUR_BRIGHT_MAGENTA,
    },
    // Gruvbox dark theme
    {
        .ink             = COLOUR_WARM_IVORY,
        .paper           = COLOUR_CHARCOAL,
        .highlight_ink   = COLOUR_AMBER,
        .highlight_paper = COLOUR_DARK_UMBER,
        .cursor          = COLOUR_WARM_IVORY,
        .gutter          = COLOUR_DARK_UMBER,
        .selection       = COLOUR_DARK_UMBER,
        .status_fg       = COLOUR_WARM_IVORY,
        .status_bg       = COLOUR_DARK_UMBER,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_PALE_CYAN,
        .link            = COLOUR_POWDER_BLUE,
        .link_visited    = COLOUR_DUSTY_BLUE,
    },
    // Solarized dark theme
    {
        .ink             = COLOUR_MISTY_SLATE,
        .paper           = COLOUR_DEEP_TEAL,
        .highlight_ink   = COLOUR_MUSTARD,
        .highlight_paper = COLOUR_SLATE_TEAL,
        .cursor          = COLOUR_MISTY_SLATE,
        .gutter          = COLOUR_SLATE_TEAL,
        .selection       = COLOUR_SLATE_TEAL,
        .status_fg       = COLOUR_MISTY_SLATE,
        .status_bg       = COLOUR_SLATE_TEAL,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_MUSTARD,
        .accent_info     = COLOUR_PALE_CYAN,
        .link            = COLOUR_POWDER_BLUE,
        .link_visited    = COLOUR_DUSTY_BLUE,
    },
    // Nord theme
    {
        .ink             = COLOUR_ICY_WHITE,
        .paper           = COLOUR_NIGHTFALL,
        .highlight_ink   = COLOUR_PALE_CYAN,
        .highlight_paper = COLOUR_STEEL,
        .cursor          = COLOUR_ICY_WHITE,
        .gutter          = COLOUR_STEEL,
        .selection       = COLOUR_STEEL,
        .status_fg       = COLOUR_ICY_WHITE,
        .status_bg       = COLOUR_STEEL,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_PALE_CYAN,
        .link            = COLOUR_PALE_CYAN,
        .link_visited    = COLOUR_DUSTY_BLUE,
    },
    // Dracula theme
    {
        .ink             = COLOUR_SOFT_WHITE,
        .paper           = COLOUR_SHADOW,
        .highlight_ink   = COLOUR_NEON_GREEN,
        .highlight_paper = COLOUR_DUSTY_BLUE,
        .cursor          = COLOUR_SOFT_WHITE,
        .gutter          = COLOUR_DUSTY_BLUE,
        .selection       = COLOUR_DUSTY_BLUE,
        .status_fg       = COLOUR_SOFT_WHITE,
        .status_bg       = COLOUR_DUSTY_BLUE,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_BRIGHT_CYAN,
        .link            = COLOUR_NEON_GREEN,
        .link_visited    = COLOUR_DUSTY_BLUE,
    },
    // Catppuccin Mocha theme
    {
        .ink             = COLOUR_PALE_LILAC,
        .paper           = COLOUR_DUSK_PURPLE,
        .highlight_ink   = COLOUR_ROSE,
        .highlight_paper = COLOUR_GRAPHITE_PURPLE,
        .cursor          = COLOUR_PALE_LILAC,
        .gutter          = COLOUR_GRAPHITE_PURPLE,
        .selection       = COLOUR_GRAPHITE_PURPLE,
        .status_fg       = COLOUR_PALE_LILAC,
        .status_bg       = COLOUR_GRAPHITE_PURPLE,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_PALE_CYAN,
        .link            = COLOUR_POWDER_BLUE,
        .link_visited    = COLOUR_DUSTY_BLUE,
    },
    // Monokai theme
    {
        .ink             = COLOUR_SOFT_WHITE,
        .paper           = COLOUR_OLIVE_BLACK,
        .highlight_ink   = COLOUR_LIME,
        .highlight_paper = COLOUR_ASH_OLIVE,
        .cursor          = COLOUR_SOFT_WHITE,
        .gutter          = COLOUR_ASH_OLIVE,
        .selection       = COLOUR_ASH_OLIVE,
        .status_fg       = COLOUR_SOFT_WHITE,
        .status_bg       = COLOUR_ASH_OLIVE,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_BRIGHT_CYAN,
        .link            = COLOUR_LIME,
        .link_visited    = COLOUR_AMBER,
    },
    // Helix-inspired dark theme
    {
        .ink             = COLOUR_FADED_IVORY,
        .paper           = COLOUR_INK_STORM,
        .highlight_ink   = COLOUR_SAGE,
        .highlight_paper = COLOUR_IRON_PURPLE,
        .cursor          = COLOUR_FADED_IVORY,
        .gutter          = COLOUR_IRON_PURPLE,
        .selection       = COLOUR_IRON_PURPLE,
        .status_fg       = COLOUR_FADED_IVORY,
        .status_bg       = COLOUR_IRON_PURPLE,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_PALE_CYAN,
        .link            = COLOUR_POWDER_BLUE,
        .link_visited    = COLOUR_DUSTY_BLUE,
    },
    // Helix default theme
    {
        .ink             = COLOUR_SOFT_GOLD,
        .paper           = COLOUR_HORIZON,
        .highlight_ink   = COLOUR_POWDER_BLUE,
        .highlight_paper = COLOUR_NIGHT_STONE,
        .cursor          = COLOUR_SOFT_GOLD,
        .gutter          = COLOUR_NIGHT_STONE,
        .selection       = COLOUR_NIGHT_STONE,
        .status_fg       = COLOUR_SOFT_GOLD,
        .status_bg       = COLOUR_NIGHT_STONE,
        .accent_error    = COLOUR_BRIGHT_RED,
        .accent_warning  = COLOUR_AMBER,
        .accent_info     = COLOUR_PALE_CYAN,
        .link            = COLOUR_POWDER_BLUE,
        .link_visited    = COLOUR_DUSTY_BLUE,
    },
};
